namespace E3DC.RSCP.Lib.Tags
{
    [TagGroup(0x0b)]
	public enum EP : uint
	{

		SWITCH_TO_GRID = 0x01,
		SWITCH_TO_ISLAND = 0x02,
		IS_READY_FOR_SWITCH = 0x03,
		IS_GRID_CONNECTED = 0x04,
		IS_ISLAND_GRID = 0x05,
		IS_INVALID_STATE = 0x06,
		IS_POSSIBLE = 0x07,
		LEAVE_INVALID_STATE_TO_ISLAND = 0x08,
		LEAVE_INVALID_STATE_TO_GRID = 0x09,
		GENERAL_ERROR = 0x007fffff,
	}
}